include:
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: rust-v1
    file:
      - '/rust.yml'

stages:
  - test
  - doc
  - publish

cargo-check:
  extends: .cargo_check

cargo-coverage:
  extends: .cargo_coverage

cargo-publish:
  extends: .cargo_publish

pages:
  extends: .cargo_doc
